# Generated by Django 3.1.6 on 2021-06-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('packed', 'packed'), ('canceled', 'canceled')], default='ordered', max_length=120),
        ),
    ]
